In [1]:
# advance indexing

import numpy as np

In [13]:
arr = np.arange(0,30, 2)
idx = [1,2,5,7,8,14]

print(arr)
print(arr[idx])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[ 2  4 10 14 16 28]


In [24]:
matrix = np.reshape(np.arange(1,21), (4,5))

rows = [2, 3, 1]
cols = [0, 4, 3]

print(matrix)
print(matrix[rows, cols])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[11 20  9]


In [ ]:
random = np.random.randint(2,100, 10)

mask = random < 18
res = random[mask]

print(mask)
print(res)
print(random[random<18])

[False  True False False False False False False  True False]
[12  5]
[12  5]


In [ ]:
arr = np.reshape(np.arange(1, 19), (3,6))
print(arr) 

arr[arr < 7] = 1
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[[ 1  1  1  1  1  1]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [48]:
arr = np.reshape(np.arange(1, 19), (3,6))
print(arr)

rows, cols = [0, 1, 2], [2,5,3]
print(arr[np.ix_(rows, cols)])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
[[ 3  6  4]
 [ 9 12 10]
 [15 18 16]]


In [53]:
arr = np.arange(20)
res = np.where(arr%2==0, 'hamza', 'odd')

print(res)

['hamza' 'odd' 'hamza' 'odd' 'hamza' 'odd' 'hamza' 'odd' 'hamza' 'odd'
 'hamza' 'odd' 'hamza' 'odd' 'hamza' 'odd' 'hamza' 'odd' 'hamza' 'odd']
